### DISCUSSION TITLE
Extending to all the things

### DISCUSSION THREAD

**Discussion by windowsrefund** [ramojus/mellifluous.nvim#68] [Ideas]
Greets,

In response to the conversation from #19 , I wanted to mention the very cool [tinted-theming/tinty](https://github.com/tinted-theming/tinty) project which may be of interest. Rather than creating and maintaining one-offs, a standard "scheme" could be created in order to setup colors for the variety of things supported by the project.

i've been dabbling a bit by simply creating a [custom scheme](https://github.com/tinted-theming/tinty/blob/main/USAGE.md#use-your-own-schemes) and so far, I'm pretty happy with the outcome. Originally, I thought I'd benefit from the palette described in #11 but that didn't get me very far as those colors don't seem to line up with reality. Of course, there's a 99% chance I don't grok the voodoo going on under the hood so maybe that palette is legit. I don't know.... 

I'm just messing around with adding tiny amounts of colors from `Melliflous` into one of my favorite base16 colorschemes, [grayscale-dark](https://github.com/tinted-theming/schemes/blob/spec-0.11/base16/grayscale-dark.yaml). I call it `Prayscale`.  I currently have tiny configured to manage colors for i3, rofi, zsh, fzf, Alacritty, and tmux

```
system: "base16"
name: "Prayscale"
author: "windowsrefund (https://github.com/windowsrefund/)"
variant: "dark"
palette:
  base00: "101010"
  base01: "252525"
  base02: "464646"
  base03: "525252"
  base04: "ababab"
  base05: "b9b9b9"
  base06: "e3e3e3"
  base07: "f7f7f7"
  base08: "7c7c7c"
  base09: "999999"
  base0A: "a0a0a0"
  base0B: "8e8e8e"
  base0C: "868686"
  base0D: "a8a1be" # mellifluous purple
  base0E: "747474"
  base0F: "5e5e5e"
```
![prayscale](https://github.com/user-attachments/assets/3a1fe3fe-c62f-4f64-bf85-219dc4ba5300)

kinda loving this!
